# Name of your GitHub Actions workflow
name: Matcha Tracker

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the job on a schedule
  schedule:
    # This runs the script every hour.
    # Use https://crontab.guru to create your own schedule.
    - cron: '0 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "run-tracker" job
  run-tracker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up a Python environment for you to use
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8' # You can change this to your preferred version

      # 3. Installs the dependencies from your requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Runs the Python script
      - name: Run the product tracker script
        # Pass the secrets to the script as environment variables
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python matcha_tracker.py